### PR TITLE
Add cond & display shortcuts

### PR DESCRIPTION
**Pull request by devonpmack**

### CODE REVIEW

**Comment by Raymo111** [comment]
What's display?

**Comment by devonpmack** [comment]
It's to print to the console, useful for debugging

**Comment by Raymo111** [comment]
Uhh what language is that? I can't get it to work for beginning student with list abbrevs

**Comment by devonpmack** [comment]
Oh I must be using a different version of racket, mb

**Comment by devonpmack** [comment]
I'll take it out

**Comment by devonpmack** [comment]
@Raymo111 is this good to go?

**Review by Raymo111 — APPROVED** [review]

**Pull request merged**
